# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greenhouse.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'greenhouse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10greenhouse.proto\x12\ngreenhouse\"P\n\x0f\x41\x63tuatorRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65viceId\x18\x02 \x01(\x03\x12\r\n\x05value\x18\x03 \x01(\x02\x12\x0e\n\x06\x61\x63tive\x18\x04 \x01(\x08\"#\n\x10\x41\x63tuatorResponse\x12\x0f\n\x07success\x18\x02 \x01(\t\"K\n\x0c\x44\x65viceStatus\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x02\x12\x0c\n\x04unit\x18\x04 \x01(\t2X\n\x0f\x41\x63tuatorService\x12\x45\n\x08setValue\x12\x1b.greenhouse.ActuatorRequest\x1a\x1c.greenhouse.ActuatorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greenhouse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTUATORREQUEST']._serialized_start=32
  _globals['_ACTUATORREQUEST']._serialized_end=112
  _globals['_ACTUATORRESPONSE']._serialized_start=114
  _globals['_ACTUATORRESPONSE']._serialized_end=149
  _globals['_DEVICESTATUS']._serialized_start=151
  _globals['_DEVICESTATUS']._serialized_end=226
  _globals['_ACTUATORSERVICE']._serialized_start=228
  _globals['_ACTUATORSERVICE']._serialized_end=316
# @@protoc_insertion_point(module_scope)
